// <auto-generated />
using System;
using LibraryAPI.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryAPI.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20251028213458_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibraryAPI.Domain.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(1965, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "J.K. Rowling"
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(1903, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "George Orwell"
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(1775, 12, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Jane Austen"
                        },
                        new
                        {
                            Id = 4,
                            DateOfBirth = new DateTime(1947, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Stephen King"
                        },
                        new
                        {
                            Id = 5,
                            DateOfBirth = new DateTime(1890, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Agatha Christie"
                        },
                        new
                        {
                            Id = 6,
                            DateOfBirth = new DateTime(1892, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "J.R.R. Tolkien"
                        },
                        new
                        {
                            Id = 7,
                            DateOfBirth = new DateTime(1899, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ernest Hemingway"
                        },
                        new
                        {
                            Id = 8,
                            DateOfBirth = new DateTime(1896, 9, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "F. Scott Fitzgerald"
                        });
                });

            modelBuilder.Entity("LibraryAPI.Domain.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("PublishedYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            PublishedYear = 1997,
                            Title = "Harry Potter and the Philosopher's Stone"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 1,
                            PublishedYear = 1998,
                            Title = "Harry Potter and the Chamber of Secrets"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 1,
                            PublishedYear = 1999,
                            Title = "Harry Potter and the Prisoner of Azkaban"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 1,
                            PublishedYear = 2000,
                            Title = "Harry Potter and the Goblet of Fire"
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 1,
                            PublishedYear = 2012,
                            Title = "The Casual Vacancy"
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 2,
                            PublishedYear = 1949,
                            Title = "1984"
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 2,
                            PublishedYear = 1945,
                            Title = "Animal Farm"
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 2,
                            PublishedYear = 1938,
                            Title = "Homage to Catalonia"
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 3,
                            PublishedYear = 1813,
                            Title = "Pride and Prejudice"
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 3,
                            PublishedYear = 1811,
                            Title = "Sense and Sensibility"
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 3,
                            PublishedYear = 1815,
                            Title = "Emma"
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 3,
                            PublishedYear = 1814,
                            Title = "Mansfield Park"
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 4,
                            PublishedYear = 1977,
                            Title = "The Shining"
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 4,
                            PublishedYear = 1986,
                            Title = "It"
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 4,
                            PublishedYear = 1978,
                            Title = "The Stand"
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 4,
                            PublishedYear = 1974,
                            Title = "Carrie"
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 4,
                            PublishedYear = 1987,
                            Title = "Misery"
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 5,
                            PublishedYear = 1934,
                            Title = "Murder on the Orient Express"
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 5,
                            PublishedYear = 1937,
                            Title = "Death on the Nile"
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 5,
                            PublishedYear = 1926,
                            Title = "The Murder of Roger Ackroyd"
                        },
                        new
                        {
                            Id = 21,
                            AuthorId = 5,
                            PublishedYear = 1939,
                            Title = "And Then There Were None"
                        },
                        new
                        {
                            Id = 22,
                            AuthorId = 6,
                            PublishedYear = 1937,
                            Title = "The Hobbit"
                        },
                        new
                        {
                            Id = 23,
                            AuthorId = 6,
                            PublishedYear = 1954,
                            Title = "The Fellowship of the Ring"
                        },
                        new
                        {
                            Id = 24,
                            AuthorId = 6,
                            PublishedYear = 1954,
                            Title = "The Two Towers"
                        },
                        new
                        {
                            Id = 25,
                            AuthorId = 6,
                            PublishedYear = 1955,
                            Title = "The Return of the King"
                        },
                        new
                        {
                            Id = 26,
                            AuthorId = 7,
                            PublishedYear = 1952,
                            Title = "The Old Man and the Sea"
                        },
                        new
                        {
                            Id = 27,
                            AuthorId = 7,
                            PublishedYear = 1929,
                            Title = "A Farewell to Arms"
                        },
                        new
                        {
                            Id = 28,
                            AuthorId = 7,
                            PublishedYear = 1940,
                            Title = "For Whom the Bell Tolls"
                        },
                        new
                        {
                            Id = 29,
                            AuthorId = 8,
                            PublishedYear = 1925,
                            Title = "The Great Gatsby"
                        },
                        new
                        {
                            Id = 30,
                            AuthorId = 8,
                            PublishedYear = 1934,
                            Title = "Tender Is the Night"
                        },
                        new
                        {
                            Id = 31,
                            AuthorId = 8,
                            PublishedYear = 1920,
                            Title = "This Side of Paradise"
                        });
                });

            modelBuilder.Entity("LibraryAPI.Domain.Models.Book", b =>
                {
                    b.HasOne("LibraryAPI.Domain.Models.Author", null)
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LibraryAPI.Domain.Models.Author", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
